### PR TITLE
Implement channel binding for the negotiate-wrapper too

### LINKED ISSUE #2: Feature request: add channel binding support
A shortage of Kerberos-over-HTTP is that there are no distinguished SPN's for HTTP- and HTTPS-services ([1](https://techcommunity.microsoft.com/t5/iis-support-blog/how-to-use-spns-when-you-configure-web-applications-thatare/ba-p/324648)). This means that a ticket that's being transmitted over an insecure HTTP-connection can also be used for HTTPS-connections to the same host. Besides this, Kerberos is also known to be vulnerable for MitM-attacks where the service-label of the SPN can be altered when an alternative service is available on the same host ([2](https://googleprojectzero.blogspot.com/2021/10/using-kerberos-for-authentication-relay.html)).

Both of these attacks can be mitigated by using RFC 5056 'channel binding' (also known as Extended Protection for Authentication ([EPA](https://msrc.microsoft.com/blog/2009/12/extended-protection-for-authentication/)) in Microsoft environments). This takes the hash of the TLS server certificate and uses it inside the cryptographic part of the protocol. This prevents that an AP-REQ messages that an attacker acquired through an insecure channel can be used and sent to a secure channel on the same host.

Currently this library has no support for passing the server certificate (hash) to the Kerberos-validator:

afbeelding

### PR DESCRIPTION
**Pull request by tvdijen**
Closes #2

### CODE REVIEW

**Comment by tvdijen** [comment]
@mbechler Is there anything that needs to be done before you can accept this?

**Comment by mbechler** [comment]
Sorry for the delay, pretty busy couple of weeks. I still wanted to look into the reference handling - the reference count needs to be adjusted. Should be able to look into that the coming week.

**Comment by tvdijen** [comment]
Thanks very much! I would do it myself, but I'm afraid this is a little beyond my skills :)  I really appreciate your help!

**Comment by mbechler** [comment]
Made the adjustment regarding the binding object reference.

Also, during my testing I realized that an additional check is needed to actually enforce the use of channel binding - otherwise the authentication would still be successful when the client does not provide binding data (in IIS this the previous behavior would be the "optional" variant, now the user has the choice). For this purpose  the isChannelBound method is added. Also adjusted the example code to reflect the new feature.

Changes are merged - please test this once again, then I'll push a release.

**Comment by tvdijen** [comment]
I will add this to my to do list for next week. Thanks so far!

**Comment by tvdijen** [comment]
Works like a charm @mbechler !

One tiny issue though.. Or maybe it's just my misunderstanding, but I was under the impression that the 3rd parameter for the constructor of KRB5NegotiateAuth was optional..  I can leave it out, but I cannot explicitly set it to null.. Is that meant to happen?

Caused by: TypeError: KRB5NegotiateAuth::__construct(): Argument #3 ($channel) must be of type GSSAPIChannelBinding, null given

**Comment by mbechler** [comment]
Only saw the rest of the the command after pushing the release. That is the default behavior, but I guess having that nullable would make usage more convient.

**Comment by tvdijen** [comment]
@mbechler One more thing that I noticed while testing that probably needs fixing is this..

When I specify the wrong hash in the binding-object, ::doAuthentication will emit a PHP warning:

```
    $binding = new GSSAPIChannelBinding();
    $binding->setApplicationData(
        'tls-server-end-point:' . pack('H*', "A1B2C3D4E5F6"),  // some hash from the wrong certificate
    );
    $auth = new KRB5NegotiateAuth($keytab, $spn, $binding);
    $auth->doAuthentication();  // Warning is being emitted

```

```
Jun 19 11:12:20 IDP[2302691]: PHP Warning:  KRB5NegotiateAuth::doAuthentication(): Success (100002)
```

With the correct hash, the warning is not emitted

**Comment by tvdijen** [comment]
One more thing.. I just deployed this to a high traffic server yesterday and since I've experienced several crashes where php-fpm would become non-responsive (no errors, it just stalls and service stays up-and-running)..  I have no hard evidence that it's related to this extension, but since it's the only thing that has changed and we've had similar issues in the past with memory management, I'm worried that a bugged PHP-extension now has been released.

To verify that it's related to this extension have downgraded back to v1.1.5 and I'm monitoring the situation.

Update 1: I was able to pull this from the logs:

```
Jun 20 14:03:50 mymachine kernel: traps: php-fpm[2284798] trap invalid opcode ip:56542ccc6144 sp:7ffec949c5c0 error:0 in php-fpm[56542c964000+4e0000]
```

**Comment by mbechler** [comment]
Will have a closer look, but unfortunately that will be another week or so till I can.

**Comment by tvdijen** [comment]
That's ok, but maybe remi needs to pull back the release? My only option to downgrade was to self-compile, because remi's repo only offered me the last 1.2.1 version to downgrade.

P.S.: so far no crashes since I've rolled back. I think I'll open a new issue for this.

**Pull request merged**
